[tool.black]
line-length = 88
target-version = ["py310"]

[tool.ruff]
line-length = 88
target-version = "py310"
select = [
    "E",
    "F",
    "I",
    "B",
]

[tool.pytest.ini_options]
addopts = "-ra"
pythonpath = ["."]

